sudo: required
services:
  - docker

before_install:
  - docker build -t amarjit01/docker-react -f dockerfile.dev .

script:
  - docker run -e CI=true amarjit01/docker-react npm run test -- --coverage
